"""Rollouts generated and rewarded by AvaCore, as the TOML at ``AVACORE_ROLLOUT_CONFIG`` defines them.

The document's ``[generate]`` and ``[reward]`` tables are structured by AvaCore; each sees a row of the
sample's metadata plus ``prompt`` and ``label``. ``${SGLANG_ROUTER_URL}`` and ``${HF_CHECKPOINT}`` name the
policy miles serves.
"""

import copy
import logging
import os
import tomllib
from argparse import Namespace
from functools import cache
from pathlib import Path
from typing import Any

import numpy as np
import pybase64
from ava_core.config import interpolated, launch_converter
from ava_core.core import TokenTrace, Trace
from ava_core.generate.core import GenerateFunction
from ava_core.generate.core import Sample as Row
from ava_core.rewards import RewardFunction
from ava_core.runner import RECOVERABLE_ERRORS

from miles.utils.types import Sample

__all__ = ["generate"]

logger = logging.getLogger(__name__)


@cache
def functions(path: str, router: str, checkpoint: str) -> tuple[GenerateFunction[Row], RewardFunction[Row]]:
    os.environ["SGLANG_ROUTER_URL"], os.environ["HF_CHECKPOINT"] = router, checkpoint
    document = tomllib.loads(Path(path).read_text())
    conv = launch_converter()
    return (
        conv.structure(interpolated(document["generate"]), GenerateFunction),
        conv.structure(interpolated(document["reward"]), RewardFunction),
    )


def flattened(trace: Trace) -> list[Trace]:
    return [trace] + [node for subtrace in trace.subtraces for node in flattened(subtrace)]


async def generate(args: Namespace, sample: Sample, sampling_params: dict[str, Any]) -> list[Sample]:
    generate_fn, reward_fn = functions(
        os.environ["AVACORE_ROLLOUT_CONFIG"],
        f"http://{args.sglang_router_ip}:{args.sglang_router_port}",
        args.hf_checkpoint,
    )
    row = Row({**sample.metadata, "prompt": sample.prompt, "label": sample.label}, key=lambda _: sample.index)
    replay = {"return_routed_experts": True} if args.use_rollout_routing_replay else {}
    try:
        trace = await generate_fn(row, sampling_params=sampling_params, **replay)
        reward = await reward_fn(trace, row)
    except RECOVERABLE_ERRORS as error:
        logger.warning("AvaCore rollout of sample %s aborted: %r", sample.index, error)
        sample.status = Sample.Status.ABORTED
        return [sample]

    assert isinstance(trace, TokenTrace), "AvaCore rollouts must drive the policy through a token-level client"
    return [
        filled(args, copy.deepcopy(sample), node, reward.score)
        for node in flattened(trace)
        if isinstance(node, TokenTrace) and any(segment.is_generated for segment in node.segments)
    ]


def filled(args: Namespace, sample: Sample, trace: TokenTrace, reward: float) -> Sample:
    # Context after the last generated turn trains nothing, and no request routed it for replay.
    segments = trace.segments[: max(i for i, segment in enumerate(trace.segments) if segment.is_generated) + 1]
    length = sum(len(segment.tokens) for segment in segments)
    prompt_length = len(segments[0].tokens)
    sample.tokens = trace.tokens[:length]
    sample.response = "".join(segment.template for segment in segments[1:])
    sample.response_length = length - prompt_length
    sample.loss_mask = trace.loss_mask[prompt_length:length]
    sample.rollout_log_probs = [log_prob or 0.0 for log_prob in trace.log_probs[prompt_length:length]]
    for message in trace.messages:
        if "finish_reason" in message.metadata:
            sample.update_from_meta_info(args, message.metadata)
    if args.use_rollout_routing_replay and sample.status != Sample.Status.ABORTED:
        assert trace.routed_experts, (
            "Internal error: routing replay enabled but no routed experts returned. Perhaps some traces are not generated by the configured generate function."
        )
        sample.rollout_routed_experts = np.frombuffer(
            b"".join(pybase64.b64decode(chunk) for chunk in trace.routed_experts), dtype=np.int32
        ).reshape(length - 1, args.num_layers, args.moe_router_topk)
    sample.reward = reward
    return sample
